openapi: "3.0.0"
info:
  title: "test"
  version: "1.0.0"
  description: "description1"
  contact:
    name: "T3"
    url: ".."
servers:
  - url: "http://api.example.com/v1"
  - url: "http://api.example.com/v1"
paths:
  /api/v1/communicationMessage:
    get:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                test:
                  type: "string"
              required:
                - "test"
      parameters:
        - in: "header"
          name: "transaction"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "transaction2"
          schema:
            type: "string"
          required: true
          description: "test"
      responses:
        200:
          description: "test"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  '@type':
                    type: "string"
                    description: "test"
                  'cancellationReason':
                    type: "string"
                    description: "test"
                  'effectiveCancellationDate':
                    type: "string"
                    description: "test"
                  'requestedCancellationDate':
                    type: "string"
                    description: "test"
                  'reserveStock':
                    type: "string"
                    description: "test"
        201:
          description: "test"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  '@type':
                    type: "string"
                    description: "test"
                  'cancellationReason':
                    type: "string"
                    description: "test"
                  'effectiveCancellationDate':
                    type: "string"
                    description: "test"
                  'requestedCancellationDate':
                    type: "string"
                    description: "test"
                  'reserveStock':
                    type: "string"
                    description: "test"
security:
  - apiKey: []
