openapi: "3.0.0"
info:
  title: "test"
  version: "1.0.0"
  description: "description1"
  contact:
    name: "T3"
    url: ".."
servers:
  - url: "http://api.example.com/v1"
  - url: "http://api.example.com/v1"
paths:
  /api/v1/communicationMessage:
    get:
      parameters:
        - in: "header"
          name: "content-type"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "user-agent"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "accept"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "cache-control"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "postman-token"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "host"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "accept-encoding"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "connection"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "content-length"
          schema:
            type: "string"
          required: true
          description: "test"
      responses:
        200:
          description: "test"
          content:
            application/json:
              schema:
                type: "string"
                example: "stom"
        201:
          description: "test"
          content:
            application/json:
              schema:
                type: "string"
                example: "stom"
security:
  - apiKey: []
