openapi: "3.0.0"
info:
  title: "test"
  version: "1.0.0"
  description: "description1"
  contact:
    name: "T3"
    url: ".."
servers:
  - url: "http://api.example.com/v1"
  - url: "http://api.example.com/v1"
paths:
  /api/v1/communicationMessage:
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                test1:
                  type: "string"
                  example: 1
                test2:
                  type: "string"
                  example: 1
                test3:
                  type: "string"
                  example: 1
                test:
                  type: "string"
                  example: 1
                asd:
                  type: "string"
                  example: 2
              required:
                - "test1"
                - "test2"
                - "test3"
      parameters:
        - in: "header"
          name: "transaction"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "transaction2"
          schema:
            type: "string"
          required: true
          description: "test"
        - in: "header"
          name: "testRequest"
          schema:
            type: "string"
          required: false
          description: "test"
        - in: "header"
          name: "testRequest2"
          schema:
            type: "string"
          required: false
          description: "test"
      responses:
        200:
          description: "case 200"
          headers:
            content-type:
              description: "content-type"
              required: true
              schema:
                type: "string"
                example: "application/json"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  '@type':
                    example: "CancelStockReservation_FVO"
                  'cancellationReason':
                    example: "string"
                  'effectiveCancellationDate':
                    example: "2024-07-30T05:12:24.597Z"
                  'requestedCancellationDate':
                    example: "2024-07-30T05:12:24.597Z"
                  'reserveStock':
                    example:
                      id: "AA240816120004"
                      '@type': "ReserveStockRef"
security:
  - apiKey: []
