openapi: "3.0.0"
info:
  title: "title name"
  version: "version api"
  description: "description"
  contact:
    name: "name contact"
    url: "url T3"
servers:
  - url: "http://localhost:8801"
  - url: "https://enpoint-test"
security:
  - apiKey: []
