openapi: "3.0.0"
info:
  title: "test"
  version: "1.0.0"
  description: "description1"
  contact:
    name: "T3"
    url: ".."
servers:
  - url: "http://localhost:8801"
  - url: "3"
paths:
  api/v1/test:
    method: "GET"
    
security:
  - apiKey: []
