openapi: "3.0.0"
info:
  title: "api01"
  version: "1.0.0"
  description: "hahahah"
  contact:
    name: "T3"
    url: "http://google.com"
servers:
  - url: "http://10.138.47.138:8080"
  - url: "https://google.com"
paths:
  /api/v1:
    get:
      tags:
        - "API TEST1"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties: {}
            example: {}
      parameters:
        - in: "header"
          name: "key"
          schema:
            type: "string"
          required: false
          description: "key"
      responses:
        200:
          description: "Success"
          headers:
            content-type:
              description: "content-type"
              required: false
              schema:
                type: "string"
                example: "app/json"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  item:
                    type: "object"
                    properties:
                      a:
                        type: "object"
                        properties:
                          d:
                            type: "array"
                            items: {}
              example:
                item:
                  a:
                    d: []
        201:
          description: "created"
          headers:
            content-type:
              description: "content-type"
              required: false
              schema:
                type: "string"
                example: "app/json"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  item:
                    type: "object"
                    properties:
                      b:
                        type: "object"
                        properties:
                          d:
                            type: "array"
                            items: {}
              example:
                item:
                  b:
                    d: []
        400:
          description: "bad request"
          headers:
            content-type:
              description: "content-type"
              required: false
              schema:
                type: "string"
                example: "app/json"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  item:
                    type: "object"
                    properties:
                      c:
                        type: "object"
                        properties:
                          d:
                            type: "array"
                            items: {}
              example:
                item:
                  c:
                    d: []
security:
  - apiKey: []
