openapi: "3.0.0"
info:
  title: "AC-Payment [ETopUp API]"
  version: "1.0.0"
  description: "Swagger ETopUp API"
  contact:
    name: "T3"
    url: ".."
servers:
  - url: "http://api.example.com/v1"
paths:
  /api/v1/eTopup:
    get:
      tags:
        - "1234"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                test3:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      test1:
                        type: "array"
                        items:
                          type: "object"
                          properties:
                            test12:
                              type: "string"
                      value:
                        type: "string"
            example: {
               test3:
                test1:
                 - test1

            }
      parameters:
        - in: "header"
          name: "mfaf-transaction"
          schema:
            type: "string"
          required: true
          description: "mfaf-transaction"
        - in: "header"
          name: "mfaf-broker"
          schema:
            type: "string"
          required: false
          description: "mfaf-broker"
        - in: "header"
          name: "mfaf-channel"
          schema:
            type: "string"
          required: false
          description: "mfaf-channel"
        - in: "header"
          name: "mfaf-device"
          schema:
            type: "string"
          required: false
          description: "mfaf-device"
        - in: "header"
          name: "mfaf-public"
          schema:
            type: "string"
          required: false
          description: "mfaf-public"
        - in: "header"
          name: "mfaf-useCase"
          schema:
            type: "string"
          required: false
          description: "mfaf-useCase"
        - in: "header"
          name: "mfaf-useCaseStep"
          schema:
            type: "string"
          required: false
          description: "mfaf-useCaseStep"
        - in: "header"
          name: "mfaf-user"
          schema:
            type: "string"
          required: false
          description: "mfaf-user"
      responses:
        200:
          description: "case 200"
          headers:
            content-type:
              description: "content-type"
              required: true
              schema:
                type: "string"
                example: "application/json"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                  message:
                    type: "string"
              example:
                status: "CTWS000"
                message: "Success"
        400:
          description: "case 400"
          headers:
            content-type:
              description: "content-type"
              required: true
              schema:
                type: "string"
                example: "application/json"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "string"
                  status:
                    type: "number"
                  message:
                    type: "string"
                  referenceError:
                    type: "string"
              example:
                code: "40300"
                status: 403
                message: "Missing or Invalid paremeter"
                referenceError: "Missing or Invalid paremeter"
security:
  - apiKey: []
